data:
  embeddings_file: data/embeddings/place_embeddings_pca128.npy
  processed_file: data/processed/gangwon_places_100_processed.csv
  raw_file: data/raw/gangwon_places_100.csv
model:
  dimensionality_reduction: PCA
  embedding_dim: 768
  reduced_dim: 128
  sbert_model: snunlp/KR-SBERT-V40K-klueNLI-augSTS
  xgboost_params:
    learning_rate: 0.1
    max_depth: 6
    n_estimators: 100
    random_state: 42
paths:
  encoders: models/encoders
  logs: logs
  models: models
